### ISSUE TITLE
Black Screen with Example Code

### ISSUE THREAD

**Issue by aidanclopp** [eliasteeny/flutter_document_scanner#25]
```
D/JavaCameraView( 6116): SUCCESS init openCV: 0
W/CameraBase( 6116): An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '10: connectHelper:1740: Failed to initialize camera "0": Function not implemented (-38)'
W/System.err( 6116): java.lang.RuntimeException: Fail to connect to camera service
```

I am receiving this error when using the posted example on the pub.dev for document_scanner. The entire screen just becomes black when I push to a page on my app that contains the example code.

I have ensured to ask the user for camera permission, and I confirmed in my emulator's settings that camera access was granted to my app. Any ideas?

**Comment by LeandroMoura3** [comment]
Here too.

There is the exception:
```
E/SurfaceView( 3424): Exception configuring surface
E/SurfaceView( 3424): java.lang.RuntimeException: setParameters failed    
E/SurfaceView( 3424):   at android.hardware.Camera.native_setParameters(Native Method)
E/SurfaceView( 3424):   at android.hardware.Camera.setParameters(Camera.java:2123)
E/SurfaceView( 3424):   at com.example.document_scanner.views.OpenNoteCameraView.surfaceCreated(OpenNoteCameraView.java:438)
E/SurfaceView( 3424):   at android.view.SurfaceView.updateSurface(SurfaceView.java:1153)
E/SurfaceView( 3424):   at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
E/SurfaceView( 3424):   at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
E/SurfaceView( 3424):   at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
E/SurfaceView( 3424):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
E/SurfaceView( 3424):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
E/SurfaceView( 3424):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
E/SurfaceView( 3424):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
E/SurfaceView( 3424):   at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/SurfaceView( 3424):   at android.view.Choreographer.doFrame(Choreographer.java:731)
E/SurfaceView( 3424):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/SurfaceView( 3424):   at android.os.Handler.handleCallback(Handler.java:938)
E/SurfaceView( 3424):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/SurfaceView( 3424):   at android.os.Looper.loop(Looper.java:223)        
E/SurfaceView( 3424):   at android.app.ActivityThread.main(ActivityThread.java:7656)
E/SurfaceView( 3424):   at java.lang.reflect.Method.invoke(Native Method)
E/SurfaceView( 3424):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/SurfaceView( 3424):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
